### ISSUE TITLE
Question about 5000 and M

### ISSUE THREAD

**Issue by LinB203** [facebookresearch/SWAG#14]
wonderful work! I am following your work to do something new.
`Next, we partition the hashtags into two sets – the head, which contains hashtags which occur in at least 5000 images`
Why do you split  the (canonical) hashtags by occuring in at least 5000 images? How to determine the number(5000)?

```
For a target number of samples, M, we sample αM samples from the head and (1−α)M samples from the tail using this sampling procedure (we chose α = 0.7).
```
The same question about M. Is it associated with total number of images(3.6B)? or the number of tail images ?

**Comment by LinB203** [comment]
How many tail images in total 3.6B images?

**Comment by mannatsingh** [comment]
@LinB203 glad you find the work useful :)

> Why do you split the (canonical) hashtags by occuring in at least 5000 images? How to determine the number(5000)?

The number 5000 was derived empirically, there isn't a good theoretical explanation for it unfortunately. You can plot the distribution of your data to find a reasonable threshold. The cutoff of 5000 images results in about half the concepts being part of the tail (even though these concepts only occur in <1% of the images). We also found that this threshold also doesn't matter much (having a head-tail partition makes a significant difference, but the exact cutoff point doesn't) when you train for long enough. For shorter training runs, this threshold does have a strong effect. 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/13458796/230978007-46fdbbe7-6983-4cdc-80e9-d4b5d0d25286.png">

> The same question about M. Is it associated with total number of images(3.6B)? or the number of tail images ?

For us, our target dataset size was 5B samples, so M = 5B. So, we got 70% * 5B = 3.5B samples from the head and 30% * 5B = 1.5B samples from the tail. The head had enough images that you can afford to get samples without ever repeating the same image, whereas in the tail we had ~12M images IIRC, so these were repeated a lot to get to 1.5B samples!

**Comment by LinB203** [comment]
> 

Thank you for your patient reply.
I noticed that 70% * 5B = 3.5B, which is very close to the original head image number (~3.6B), can I assume that fixing the hyperparameter 70% makes the number of head images after resampling basically the same as the original head image number? If so, then we can get 3.6 / 70% ≈ 5.1B, which is very close to the target daataset size (5B).

By the way, what does IIRC mean?

**Comment by LinB203** [comment]
Are you resampling head images and tail images independently and separately? In 3.6B head images are sampled at 3.5B and in 12M tail images are resampled to 1.5B, am I right?

**Comment by mannatsingh** [comment]
@LinB203 you're welcome!

IIRC = "if I remember correctly", sorry for the acronym!

> Are you resampling head images and tail images independently and separately? In 3.6B head images are sampled at 3.5B and in 12M tail images are resampled to 1.5B, am I right?

Yes, this is correct. 

Let's say that the original number of head images before resampling is `H` and the original tail images is `T`. Now, let's say that we want to create a target dataset of size `M` (`M` was 5 billion for us). We will sample `0.7 M` samples from the set of `H` head images and `0.3 M` samples from the set of `T` tail images. In practice, `T` is 12 million, whereas `H` is even greater than 5 billion. Since we only select 3.5B images from the head, the remaining images from the head will be unused.

Hope this clarifies things :)

> Are you resampling head images and tail images independently and separately? In 3.6B head images are sampled at 3.5B and in 12M tail images are resampled to 1.5B, am I right?

Yes, that is correct!

**Comment by LinB203** [comment]
> @LinB203不客气！
> 
> IIRC =“如果我没记错的话”，对不起首字母缩写词！
> 
> > 您是否独立且分开地重新采样头部图像和尾部图像？在 3.6B 中，头部图像以 3.5B 采样，在 12M 中，尾部图像以 1.5B 重新采样，对吗？
> 
> 是的，这是正确的。
> 
> 假设重采样前的原始头部图像数量为`H`，原始尾部图像数量为`T`。现在，假设我们要创建一个大小为 50 亿的目标数据`M`集`M`。`0.7 M`我们将从一组`H`头部图像和`0.3 M`一组尾部图像中采样样本`T`。实际上，`T`是 1200 万，而`H`是甚至大于 50 亿。由于我们只选择头部的 3.5B 图像，因此头部的其余图像将不会被使用。
> 
> 希望这能澄清事情:)
> 
> > 您是否独立且分开地重新采样头部图像和尾部图像？在 3.6B 中，头部图像以 3.5B 采样，在 12M 中，尾部图像以 1.5B 重新采样，对吗？
> 
> 对，那是正确的！

Sorry to bother you again.
I would like to confirm again why `H` is greater than 5B? According to the previous understanding it should be` H + T = 3.6B`, where `T = 12M`, did I miss something?

**Comment by mannatsingh** [comment]
Yes, so `H` is the original unprocessed data, which was greater than 5B for us. We needed only 3.5B images from the head to produce the target 5B dataset (3.5B from head and 1.5B from tail). After running our pipeline, we only use a subset of the original unprocessed, let's call it `H^`. 

`H^ + T = 3.6B`, where `T = 12M`.

**Comment by LinB203** [comment]
Thank you for your clear reply.
